// Code generated by protoc-gen-go.
// source: bitbox.proto
// DO NOT EDIT!

/*
Package angrypie_bitbox is a generated protocol buffer package.

It is generated from these files:
	bitbox.proto

It has these top-level messages:
	StartRequest
	StatusResponse
	GenerateRequest
	NodeRequest
	SendRequest
	BalanceResponse
	AddressResponse
	Empty
*/
package angrypie_bitbox

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StartRequest struct {
	// Number of bicoind nodes to be started
	Nodes int32 `protobuf:"varint,1,opt,name=nodes" json:"nodes,omitempty"`
}

func (m *StartRequest) Reset()                    { *m = StartRequest{} }
func (m *StartRequest) String() string            { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()               {}
func (*StartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StartRequest) GetNodes() int32 {
	if m != nil {
		return m.Nodes
	}
	return 0
}

type StatusResponse struct {
	Status bool   `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StatusResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *StatusResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GenerateRequest struct {
	// Id of bicoind node
	Node int32 `protobuf:"varint,1,opt,name=node" json:"node,omitempty"`
	// Number of block
	Blocks int32 `protobuf:"varint,2,opt,name=blocks" json:"blocks,omitempty"`
}

func (m *GenerateRequest) Reset()                    { *m = GenerateRequest{} }
func (m *GenerateRequest) String() string            { return proto.CompactTextString(m) }
func (*GenerateRequest) ProtoMessage()               {}
func (*GenerateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GenerateRequest) GetNode() int32 {
	if m != nil {
		return m.Node
	}
	return 0
}

func (m *GenerateRequest) GetBlocks() int32 {
	if m != nil {
		return m.Blocks
	}
	return 0
}

type NodeRequest struct {
	// node index
	Node int32 `protobuf:"varint,1,opt,name=node" json:"node,omitempty"`
}

func (m *NodeRequest) Reset()                    { *m = NodeRequest{} }
func (m *NodeRequest) String() string            { return proto.CompactTextString(m) }
func (*NodeRequest) ProtoMessage()               {}
func (*NodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NodeRequest) GetNode() int32 {
	if m != nil {
		return m.Node
	}
	return 0
}

type SendRequest struct {
	// Id of bicoind node
	Node int32 `protobuf:"varint,1,opt,name=node" json:"node,omitempty"`
	// bitcoin address
	Address string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	// bitcoin to spend
	Amount float64 `protobuf:"fixed64,3,opt,name=amount" json:"amount,omitempty"`
}

func (m *SendRequest) Reset()                    { *m = SendRequest{} }
func (m *SendRequest) String() string            { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()               {}
func (*SendRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SendRequest) GetNode() int32 {
	if m != nil {
		return m.Node
	}
	return 0
}

func (m *SendRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SendRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type BalanceResponse struct {
	Balance float64 `protobuf:"fixed64,1,opt,name=balance" json:"balance,omitempty"`
}

func (m *BalanceResponse) Reset()                    { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string            { return proto.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()               {}
func (*BalanceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BalanceResponse) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type AddressResponse struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *AddressResponse) Reset()                    { *m = AddressResponse{} }
func (m *AddressResponse) String() string            { return proto.CompactTextString(m) }
func (*AddressResponse) ProtoMessage()               {}
func (*AddressResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AddressResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*StartRequest)(nil), "angrypie.bitbox.StartRequest")
	proto.RegisterType((*StatusResponse)(nil), "angrypie.bitbox.StatusResponse")
	proto.RegisterType((*GenerateRequest)(nil), "angrypie.bitbox.GenerateRequest")
	proto.RegisterType((*NodeRequest)(nil), "angrypie.bitbox.NodeRequest")
	proto.RegisterType((*SendRequest)(nil), "angrypie.bitbox.SendRequest")
	proto.RegisterType((*BalanceResponse)(nil), "angrypie.bitbox.BalanceResponse")
	proto.RegisterType((*AddressResponse)(nil), "angrypie.bitbox.AddressResponse")
	proto.RegisterType((*Empty)(nil), "angrypie.bitbox.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Bitbox service

type BitboxClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	Balance(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	Address(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*AddressResponse, error)
}

type bitboxClient struct {
	cc *grpc.ClientConn
}

func NewBitboxClient(cc *grpc.ClientConn) BitboxClient {
	return &bitboxClient{cc}
}

func (c *bitboxClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/angrypie.bitbox.Bitbox/Start", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bitboxClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/angrypie.bitbox.Bitbox/Generate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bitboxClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/angrypie.bitbox.Bitbox/Send", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bitboxClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/angrypie.bitbox.Bitbox/Stop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bitboxClient) Balance(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := grpc.Invoke(ctx, "/angrypie.bitbox.Bitbox/Balance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bitboxClient) Address(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*AddressResponse, error) {
	out := new(AddressResponse)
	err := grpc.Invoke(ctx, "/angrypie.bitbox.Bitbox/Address", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Bitbox service

type BitboxServer interface {
	Start(context.Context, *StartRequest) (*StatusResponse, error)
	Generate(context.Context, *GenerateRequest) (*StatusResponse, error)
	Send(context.Context, *SendRequest) (*StatusResponse, error)
	Stop(context.Context, *Empty) (*StatusResponse, error)
	Balance(context.Context, *NodeRequest) (*BalanceResponse, error)
	Address(context.Context, *NodeRequest) (*AddressResponse, error)
}

func RegisterBitboxServer(s *grpc.Server, srv BitboxServer) {
	s.RegisterService(&_Bitbox_serviceDesc, srv)
}

func _Bitbox_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitboxServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/angrypie.bitbox.Bitbox/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitboxServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bitbox_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitboxServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/angrypie.bitbox.Bitbox/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitboxServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bitbox_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitboxServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/angrypie.bitbox.Bitbox/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitboxServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bitbox_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitboxServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/angrypie.bitbox.Bitbox/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitboxServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bitbox_Balance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitboxServer).Balance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/angrypie.bitbox.Bitbox/Balance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitboxServer).Balance(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bitbox_Address_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitboxServer).Address(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/angrypie.bitbox.Bitbox/Address",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitboxServer).Address(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bitbox_serviceDesc = grpc.ServiceDesc{
	ServiceName: "angrypie.bitbox.Bitbox",
	HandlerType: (*BitboxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Bitbox_Start_Handler,
		},
		{
			MethodName: "Generate",
			Handler:    _Bitbox_Generate_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _Bitbox_Send_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Bitbox_Stop_Handler,
		},
		{
			MethodName: "Balance",
			Handler:    _Bitbox_Balance_Handler,
		},
		{
			MethodName: "Address",
			Handler:    _Bitbox_Address_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bitbox.proto",
}

func init() { proto.RegisterFile("bitbox.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x93, 0xd1, 0x4a, 0xfb, 0x30,
	0x14, 0xc6, 0x97, 0xff, 0xd6, 0x75, 0xff, 0xb3, 0xe1, 0x24, 0xc8, 0x28, 0x43, 0xb1, 0x06, 0x2f,
	0x06, 0x42, 0x2f, 0xf4, 0x4e, 0xf0, 0x62, 0x03, 0x19, 0x22, 0x28, 0xa4, 0x4f, 0x90, 0xae, 0x61,
	0x0c, 0xb7, 0xa4, 0x36, 0x19, 0xb8, 0x57, 0xf4, 0xa9, 0x24, 0x69, 0xaa, 0xb5, 0x1d, 0x63, 0xde,
	0xe5, 0x3b, 0xfd, 0xf2, 0x9d, 0xe4, 0xfc, 0x1a, 0x18, 0x24, 0x2b, 0x9d, 0xc8, 0x8f, 0x28, 0xcb,
	0xa5, 0x96, 0x78, 0xc8, 0xc4, 0x32, 0xdf, 0x65, 0x2b, 0x1e, 0x15, 0x65, 0x72, 0x0d, 0x83, 0x58,
	0xb3, 0x5c, 0x53, 0xfe, 0xbe, 0xe5, 0x4a, 0xe3, 0x33, 0xf0, 0x84, 0x4c, 0xb9, 0x0a, 0x50, 0x88,
	0x26, 0x1e, 0x2d, 0x04, 0xb9, 0x87, 0x93, 0x58, 0x33, 0xbd, 0x55, 0x94, 0xab, 0x4c, 0x0a, 0xc5,
	0xf1, 0x08, 0xba, 0xca, 0x56, 0xac, 0xb1, 0x47, 0x9d, 0xc2, 0xa7, 0xd0, 0xde, 0xa8, 0x65, 0xf0,
	0x2f, 0x44, 0x93, 0xff, 0xd4, 0x2c, 0xc9, 0x03, 0x0c, 0xe7, 0x5c, 0xf0, 0x9c, 0x69, 0x5e, 0x36,
	0xc1, 0xd0, 0x31, 0xb9, 0xae, 0x87, 0x5d, 0x9b, 0xc0, 0x64, 0x2d, 0x17, 0x6f, 0xca, 0xee, 0xf5,
	0xa8, 0x53, 0xe4, 0x0a, 0xfa, 0x2f, 0x32, 0x3d, 0xb4, 0x95, 0xc4, 0xd0, 0x8f, 0xb9, 0x48, 0x0f,
	0xa5, 0x07, 0xe0, 0xb3, 0x34, 0xcd, 0xb9, 0x52, 0xee, 0x68, 0xa5, 0x34, 0x7d, 0xd9, 0x46, 0x6e,
	0x85, 0x0e, 0xda, 0x21, 0x9a, 0x20, 0xea, 0x14, 0xb9, 0x81, 0xe1, 0x8c, 0xad, 0x99, 0x58, 0xf0,
	0xef, 0x3b, 0x07, 0xe0, 0x27, 0x45, 0xc9, 0x66, 0x23, 0x5a, 0x4a, 0x63, 0x9e, 0x16, 0x79, 0x55,
	0x73, 0xd9, 0x11, 0xfd, 0xea, 0x48, 0x7c, 0xf0, 0x1e, 0x37, 0x99, 0xde, 0xdd, 0x7e, 0xb6, 0xa1,
	0x3b, 0xb3, 0x18, 0xf0, 0x13, 0x78, 0x16, 0x03, 0xbe, 0x88, 0x6a, 0x84, 0xa2, 0x2a, 0x9e, 0xf1,
	0xe5, 0xbe, 0xcf, 0x15, 0x2e, 0xa4, 0x85, 0x5f, 0xa1, 0x57, 0xce, 0x1b, 0x87, 0x0d, 0x7b, 0x0d,
	0xc5, 0x31, 0x81, 0x73, 0xe8, 0x98, 0xf1, 0xe2, 0xf3, 0xa6, 0xf5, 0x67, 0xea, 0xc7, 0x04, 0x4d,
	0xa1, 0x13, 0x6b, 0x99, 0xe1, 0x51, 0xc3, 0x6a, 0xe7, 0x71, 0x4c, 0xc4, 0x33, 0xf8, 0x8e, 0xca,
	0x9e, 0xe3, 0x54, 0xfe, 0x93, 0x71, 0xf3, 0xe6, 0x35, 0x9a, 0x45, 0x98, 0xa3, 0xf6, 0xe7, 0xb0,
	0x1a, 0x6d, 0xd2, 0x4a, 0xba, 0xf6, 0x81, 0xdd, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x87,
	0x94, 0xb0, 0x70, 0x03, 0x00, 0x00,
}
